# Site settings
title: Usiel Ramírez González
email: usi_josue@hotmail.com
url: https://usielr12.github.io/
description: Página persona donde abarco mis estudios, cursos más relevantes que he tomado, habilidades, intereses, CV y entre otros
keywords: Usiel Ramírez González, Usiel, Ramírez, González, Perfil profesional, experiencia laboral, habilidades destacadas, portafolio de trabajo, trayectoria laboral
skills: Estudiante - Desarrollador Web - Automatización QA
meta_author: Ramírez González Usiel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Usiel

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Usiel Ramírez González
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/usielramirez_12
  - title: facebook
    url: https://www.facebook.com/uziel.ramirez.77/
  - title: Instagram
    url: https://www.instagram.com/usielrmz/
  - title: Linkedin
    url: https://www.linkedin.com/in/usiel-ram%C3%ADrez-gonz%C3%A1lez-7a7090249/
  - title: github
    url: https://github.com/UsielR12

# Postal address (add as many lines as necessary)
address:
  - line: Costa Rica
  - line: Cartago

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
